### ISSUE TITLE
descriptionDisplay extension mappings

### ISSUE THREAD

**Issue by artronics** [NHSDigital/fhir-transforms#41] opened 2022-02-28 13:44 UTC
[AMB-1029](https://nhsd-jira.digital.nhs.uk/browse/AMB-1029) captures the requirement for this ticket. The state/usage of this extension is exactly the same as `descriptionId` which I opened a separate issue [here](https://github.com/NHSDigital/fhir-transforms/issues/38).

**Comment by declankieran** [comment] 2022-03-16 13:25
Duplicate of https://github.com/NHSDigital/fhir-transforms/issues/38

**Closed as completed by declankieran** 2022-03-16 13:25 UTC
